### PR TITLE
Add support section to README

### PR DESCRIPTION
**Pull request by dagingaa**
This change adds a small text about support, that basically states that appear.in cannot be held responsible for supporting this application, as it is unofficial.

Note from the team:
Thanks for creating something like this! I'm Dag-Inge, and I am the tech lead of the appear.in premium project. In addition, I also do a lot of the API stuff and developer relations, which is why I'm reaching out to you here.

We've had a similar project internally, but due to resource constraints, we haven't had time to develop it further or release it, as we would have to officially support it as well. Though this might change in the future, I believe your project will be enough for a lot of users requesting something like this.

As to your questions posed in the 0.9 release. We're fine with you using our logo and name for this, as long as it's made clear that the application is unofficial, now and in the future. Preferably, we would like to have the installed application name be something like "appear.in (unofficial)" in case we one day decide to release our own desktop alternative. In addition, it is strongly encouraged that the application is a simple wrapper around the most recent web version, that is, make it actually fetch our index.html every time it loads the app. We do not do versioned releases of our web frontend, nor do we do anything special to support older versions of it currently, so to make this work in most cases, you want to keep loading our frontend instead of caching it in each release.

We love what you're doing, and the time and effort you've put down in this, and hopefully in the future as well. We can't offer much, but we would like to send you, and contributors to this project, some swag as a token of our appreciation. Please get in touch at pro@appear.in with your postal address and t-shirt size, and we'll send some your way.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> it is strongly encouraged that the application is a simple wrapper around the most recent web version, that is, make it actually fetch our index.html every time it loads the app.

Wouldn’t have it any other way. That’s how it works now, and I have no intention of changing that. The biggest things the app does on top of the website (and it always happens after loading your online version) are shifting the logo a bit to the right (because of the close/minimise/maximize buttons) and grab notifications so it can bounce the dock icon and put a little badge on it.

To clarify why releases exist at all, it’s to fix problems with the app itself. Some examples as to why I may need to release new versions:

+ Add support to other operating systems.
+ In case you’ve made some change on the website that breaks the app in some way that I need to fix.
+ Add support for new features (currently the app cannot screen share, for example, since [Electron does not support Chrome extensions](https://github.com/electron/electron/issues/1498), but that might change in the future).

> Preferably, we would like to have the installed application name be something like "appear.in (unofficial)" in case we one day decide to release our own desktop alternative. 

What if I promise in the README to retire this app if you ever release an official one, which would you prefer? There’s really no reason for me not to do that, anyway, since an official app would be able to do more than what I can, right now.

Just let me know which one you’d rather have (a promise on the README to retire the app or changing it’s name to `appear.in (unofficial).app`), and I’ll make the change.

Finally, I don’t mind at all being even clearer that this app is unofficial. How about [like this](https://github.com/vitorgalvao/appear.in/pull/2/files)?

Thank you for taking the time to respond and letting me use the name and logo, and on such short notice, even!

**Comment by dagingaa** [comment]
> What if I promise in the README to retire this app if you ever release an official one, which would you prefer? There’s really no reason for me not to do that, anyway, since an official app would be able to do more than what I can, right now.

> Just let me know which one you’d rather have (a promise on the README to retire the app or changing it’s name to appear.in (unofficial).app), and I’ll make the change.

> Finally, I don’t mind at all being even clearer that this app is unofficial. How about like this?

You suggestion looks like just what we're looking for. Have that in the README, and you can go ahead and keep the name of the app appear.in for installed users. As for what we'll do if we release an official version, I don't have any good suggestion, and I don't think we need to have a discussion on that now. Neither of us are lawyers, but honest people, so I imagine we'll be able to figure something out just fine when the time comes. Besides, people might enjoy your version more, in which case I think they should be able to continue using what they prefer, and not have us dictate that. We're all about user experience anyway.

To be explicit: You have our permission to use the appear.in logo and name for your unofficial desktop application, given that https://github.com/vitorgalvao/appear.in/pull/2/files is merged into the README, and that it is clear at all times that the client is unofficial through a notice in the README. Other than that, I don't think we need more clarification, but should instead keep in touch and follow each others work to best align our common interests, making communication great again ;)

Thanks again!

**Comment by vitorgalvao** [comment]
> I imagine we'll be able to figure something out just fine when the time comes.

Agreed.

> Besides, people might enjoy your version more, in which case I think they should be able to continue using what they prefer, and not have us dictate that.

Contrary to the case with Fog/Overcast, where the extra features were something I wanted to add, with appear.in I mostly want it to be as faithful as possible to the website. With that in mind, I doubt users will prefer this unofficial version to any official one you may release, but if that is the case, we can discuss this again and follow whichever route you prefer.

I’ll even do you one better. I’m currently the lead maintainer of [homebrew-cask](https://github.com/caskroom/homebrew-cask), and I’ll add this app there. If you ever release an official one, as part of retiring this one I’ll also change the file there to point to yours. Even if I eventually leave the project, we have clear rules in place that should ensure that happens (mine would be renamed `vitorgalvao-appearin` if it were to remain).

I’ve [updated #2](https://github.com/vitorgalvao/appear.in/pull/2/files) with the notice about retiring the app. If there are no objections, I’ll merge it in later today or early tomorrow.

> Other than that, I don't think we need more clarification, but should instead keep in touch and follow each others work to best align our common interests, making communication great again

Sounds great. Thank you again for all your availability. Have a nice day!

**Comment by dagingaa** [comment]
> I’ll even do you one better. I’m currently the lead maintainer of homebrew-cask, and I’ll add this app there. If you ever release an official one, as part of retiring this one I’ll also change the file there to point to yours. Even if I eventually leave the project, we have clear rules in place that should ensure that happens (mine would be renamed vitorgalvao-appearin if it were to remain).

We would love that! We also use homebrew quite extensively, most of the team is OSX based.

#2 is approved, so go ahead and merge for our sake. Thanks again!

**Pull request closed without merging**
